"""Add source column to recognition_history

Revision ID: 30c5bfc5b43b
Revises: b90226ee2bc0
Create Date: 2025-06-11 16:08:50.927394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic
revision = '30c5bfc5b43b'
down_revision = 'b90226ee2bc0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_albums_id'), 'albums', ['id'], unique=False)
    op.create_index(op.f('ix_artists_id'), 'artists', ['id'], unique=False)
    op.add_column('recognition_history', sa.Column('source', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_songs_id'), 'songs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_songs_id'), table_name='songs')
    op.drop_column('recognition_history', 'source')
    op.drop_index(op.f('ix_artists_id'), table_name='artists')
    op.drop_index(op.f('ix_albums_id'), table_name='albums')
    # ### end Alembic commands ### 