services:
  # PostgreSQL Database
  postgres:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"

  # MongoDB Database
  mongo:
    image: mongo:5.0
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

  # Redis for Celery
  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"

  # Your Application Service (runs both API and Worker)
  api:
    build:
      context: .
      dockerfile: deploy/Dockerfile
    command: ./run.sh
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - postgres
      - mongo
      - redis

volumes:
  postgres_data:
  mongo_data: