name: Test and Deploy to Render

on:
  push:
    branches: [ main ] # Or your default branch
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run Python Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # If you have dev-requirements.txt for tests
          if [ -f dev-requirements.txt ]; then pip install -r dev-requirements.txt; fi

      - name: Run tests with pytest
        env:
          # You might need to set dummy env vars for tests
          DATABASE_URL: "sqlite:///:memory:"
          CELERY_BROKER_URL: "redis://localhost:6379/0"
        run: |
          pytest

  deploy:
    name: Deploy to Render
    runs-on: ubuntu-latest
    needs: test # This job only runs if the 'test' job succeeds
    # Only run this job on a push to the main branch, not on PRs
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - name: Trigger Render Deploy for API
        run: curl "${{ secrets.RENDER_DEPLOY_HOOK_API }}"

      - name: Trigger Render Deploy for Worker
        run: curl "${{ secrets.RENDER_DEPLOY_HOOK_WORKER }}"